# Generated by Django 2.2 on 2019-04-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(max_length=253, primary_key=True, serialize=False)),
                ('current_month', models.IntegerField()),
                ('odd_month', models.IntegerField()),
                ('even_month', models.IntegerField()),
                ('odd_month_num_visited', models.IntegerField(default=0)),
                ('even_month_num_visited', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('url', models.CharField(max_length=2083)),
                ('shortenURL', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('numVisited', models.IntegerField(default=0)),
            ],
        ),
    ]
