# Generated by Django 2.2 on 2019-04-10 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
